// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBcoShgChPJWw5Kc04xDU9kohWk31DdmKI',
    appId: '1:504252717389:web:669315eabdcc1094467f04',
    messagingSenderId: '504252717389',
    projectId: 'admin-elith',
    authDomain: 'admin-elith.firebaseapp.com',
    storageBucket: 'admin-elith.firebasestorage.app',
    measurementId: 'G-2ZL6R2K8GK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDA5ovRLJ0buXegStzU64nIXVroAfd_MGw',
    appId: '1:504252717389:android:8befb8646cb238b9467f04',
    messagingSenderId: '504252717389',
    projectId: 'admin-elith',
    storageBucket: 'admin-elith.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCjq2YfIBwDvPPZKCKjLyJwB924F-psHTo',
    appId: '1:504252717389:ios:df6b144c5eb63827467f04',
    messagingSenderId: '504252717389',
    projectId: 'admin-elith',
    storageBucket: 'admin-elith.firebasestorage.app',
    iosBundleId: 'com.elith.admin',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCjq2YfIBwDvPPZKCKjLyJwB924F-psHTo',
    appId: '1:504252717389:ios:df6b144c5eb63827467f04',
    messagingSenderId: '504252717389',
    projectId: 'admin-elith',
    storageBucket: 'admin-elith.firebasestorage.app',
    iosBundleId: 'com.elith.admin',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBcoShgChPJWw5Kc04xDU9kohWk31DdmKI',
    appId: '1:504252717389:web:7e4cdc5fc5fb781e467f04',
    messagingSenderId: '504252717389',
    projectId: 'admin-elith',
    authDomain: 'admin-elith.firebaseapp.com',
    storageBucket: 'admin-elith.firebasestorage.app',
    measurementId: 'G-PBRMGGDYBS',
  );
}
