import 'package:admin/themes/theme_data_extention.dart';
import 'package:flutter/material.dart';


const kFontFamily = "";

class BlueTheme {
  static ColorScheme lightScheme() => const ColorScheme(
    brightness: Brightness.light,
    primary: Color(0xff006591),
    surfaceTint: Color(0xff006591),
    onPrimary: Color(0xffffffff),
    primaryContainer: Color(0xff009cde),
    onPrimaryContainer: Color(0xff002f46),
    secondary: Color(0xff006591),
    onSecondary: Color(0xffffffff),
    secondaryContainer: Color(0xff009cde),
    onSecondaryContainer: Color(0xff002f46),
    tertiary: Color(0xff006591),
    onTertiary: Color(0xffffffff),
    tertiaryContainer: Color(0xff009cde),
    onTertiaryContainer: Color(0xff002f46),
    error: Color(0xffba1a1a),
    onError: Color(0xffffffff),
    errorContainer: Color(0xffffdad6),
    onErrorContainer: Color(0xff93000a),
    surface: Color(0xfff6faff),
    onSurface: Color(0xff171c20),
    onSurfaceVariant: Color(0xff3e4850),
    outline: Color(0xff6e7881),
    outlineVariant: Color(0xffbec8d1),
    shadow: Color(0xff000000),
    scrim: Color(0xff000000),
    inverseSurface: Color(0xff2c3135),
    inversePrimary: Color(0xff89ceff),
    primaryFixed: Color(0xffc9e6ff),
    onPrimaryFixed: Color(0xff001e2f),
    primaryFixedDim: Color(0xff89ceff),
    onPrimaryFixedVariant: Color(0xff004c6e),
    secondaryFixed: Color(0xffc9e6ff),
    onSecondaryFixed: Color(0xff001e2f),
    secondaryFixedDim: Color(0xff89ceff),
    onSecondaryFixedVariant: Color(0xff004c6e),
    tertiaryFixed: Color(0xffc9e6ff),
    onTertiaryFixed: Color(0xff001e2f),
    tertiaryFixedDim: Color(0xff89ceff),
    onTertiaryFixedVariant: Color(0xff004c6e),
    surfaceDim: Color(0xffd6dae0),
    surfaceBright: Color(0xfff6faff),
    surfaceContainerLowest: Color(0xffffffff),
    surfaceContainerLow: Color(0xfff0f4fa),
    surfaceContainer: Color(0xffeaeef4),
    surfaceContainerHigh: Color(0xffe4e8ee),
    surfaceContainerHighest: Color(0xffdfe3e8),
  );

  ThemeData light() => theme(lightScheme());

  static ColorScheme darkScheme() => const ColorScheme(
    brightness: Brightness.dark,
    primary: Color(0xff89ceff),
    surfaceTint: Color(0xff89ceff),
    onPrimary: Color(0xff00344d),
    primaryContainer: Color(0xff009cde),
    onPrimaryContainer: Color(0xff002f46),
    secondary: Color(0xff89ceff),
    onSecondary: Color(0xff00344d),
    secondaryContainer: Color(0xff009cde),
    onSecondaryContainer: Color(0xff002f46),
    tertiary: Color(0xff89ceff),
    onTertiary: Color(0xff00344d),
    tertiaryContainer: Color(0xff009cde),
    onTertiaryContainer: Color(0xff002f46),
    error: Color(0xffffb4ab),
    onError: Color(0xff690005),
    errorContainer: Color(0xff93000a),
    onErrorContainer: Color(0xffffdad6),
    surface: Color(0xff0f1418),
    onSurface: Color(0xffdfe3e8),
    onSurfaceVariant: Color(0xffbec8d1),
    outline: Color(0xff88929b),
    outlineVariant: Color(0xff3e4850),
    shadow: Color(0xff000000),
    scrim: Color(0xff000000),
    inverseSurface: Color(0xffdfe3e8),
    inversePrimary: Color(0xff006591),
    primaryFixed: Color(0xffc9e6ff),
    onPrimaryFixed: Color(0xff001e2f),
    primaryFixedDim: Color(0xff89ceff),
    onPrimaryFixedVariant: Color(0xff004c6e),
    secondaryFixed: Color(0xffc9e6ff),
    onSecondaryFixed: Color(0xff001e2f),
    secondaryFixedDim: Color(0xff89ceff),
    onSecondaryFixedVariant: Color(0xff004c6e),
    tertiaryFixed: Color(0xffc9e6ff),
    onTertiaryFixed: Color(0xff001e2f),
    tertiaryFixedDim: Color(0xff89ceff),
    onTertiaryFixedVariant: Color(0xff004c6e),
    surfaceDim: Color(0xff0f1418),
    surfaceBright: Color(0xff353a3e),
    surfaceContainerLowest: Color(0xff0a0f13),
    surfaceContainerLow: Color(0xff171c20),
    surfaceContainer: Color(0xff1b2024),
    surfaceContainerHigh: Color(0xff262b2f),
    surfaceContainerHighest: Color(0xff30353a),
  );



  ThemeData dark() => theme(darkScheme());

  ThemeData theme(ColorScheme colorScheme) => ThemeData(
    colorScheme: colorScheme,
    primaryColor: colorScheme.primary,
    primaryColorDark: colorScheme.primary,
    fontFamily: kFontFamily,
    scaffoldBackgroundColor: colorScheme.surfaceContainerLowest,
    cardTheme: ThemeDataExtension.cardTheme(colorScheme),
    dividerTheme: ThemeDataExtension.devidedTheme(colorScheme),
    textTheme: ThemeDataExtension.textThemeData(colorScheme),
    dividerColor: colorScheme.outline,
    elevatedButtonTheme: ThemeDataExtension.elevatedButtonTheme(colorScheme),
    disabledColor: colorScheme.outline,
    hintColor: colorScheme.outline,
    shadowColor: colorScheme.outline.withOpacity(0.5),
    dialogTheme: ThemeDataExtension.dialogTheme(colorScheme),
    bottomSheetTheme: ThemeDataExtension.bottomsheetTheme(colorScheme),
    inputDecorationTheme: ThemeDataExtension.inputDecorationTheme(colorScheme),
    radioTheme: ThemeDataExtension.radioTheme(colorScheme),
    checkboxTheme: ThemeDataExtension.checkboxTheme(colorScheme),
    floatingActionButtonTheme: ThemeDataExtension.floatingActionButtonTheme(colorScheme),
    snackBarTheme: ThemeDataExtension.snackBarTheme(colorScheme),
    appBarTheme: ThemeDataExtension.appBarTheme(colorScheme),
  );
}

